### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by tqosu** [qingyanbaby/poe_2_openai#13]
```
# python demo
from openai import OpenAI

client = OpenAI(
  # 自定义校验token
  api_key='sk-xxxxxxxxxxxxx',
  base_url='http://127.0.0.1:39527/v1'
)
messages = [
  {"role": "system", "content": "You are a helpful assistant."},
  {"role": "user", "content": "Hello, who won the world series in 2020?"}
]
response = client.chat.completions.create(
  model="gpt-4o",
  messages=messages,
  stream=False
)

print(response.choices[0].message)
```

I tried the example code and got this error.

INFO:     127.0.0.1:44732 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error

Any ideas to address it? Thanks.

**Comment by qingyanbaby** [comment]
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/6287c360-b96e-4580-9713-3406e18c8669" />
I tested it and there were no issues. Have you configured the correct model mapping and the correct POE API key? Or you can paste the error logs from the service.

**Comment by tqosu** [comment]
python run.py
DEBUG:asyncio:Using selector: EpollSelector
INFO:     Started server process [2877722]
INFO:     Waiting for application startup.
Starting up...
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:39527 (Press CTRL+C to quit)
INFO:     127.0.0.1:52614 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52614 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52618 - "GET /v1/models HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:59588 - "GET /v1/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:54536 - "GET / HTTP/1.1" 200 OK

**Comment by tqosu** [comment]
I copied the API key from https://poe.com/api_key to replace the xxxxxxxxxxxxx part.
It seems the initial part fails (above). But I do not know how to address it.

**Comment by tqosu** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/tq/scratch1/2024/12/25/poe_2_openai/main.py", line 23, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/tq/scratch1/2024/12/25/poe_2_openai/route/route_chat.py", line 39, in chat_proxy
    return await default_response(model, messages, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/tq/scratch1/2024/12/25/poe_2_openai/route/route_chat.py", line 100, in default_response
    result = await poe_api.get_responses(token, messages, model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/tq/scratch1/2024/12/25/poe_2_openai/api/poe_api.py", line 36, in get_responses
    return await get_final_response(query, bot_name=bot_name, api_key=api_key, session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/fastapi_poe/client.py", line 593, in get_final_response
    async for message in stream_request(
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/fastapi_poe/client.py", line 350, in stream_request
    async for message in stream_request_base(
  File "/home/tq/miniconda3/envs/myenv/lib/python3.11/site-packages/fastapi_poe/client.py", line 508, in stream_request_base
    raise BotError(f"Error communicating with bot {bot_name}") from e
fastapi_poe.client.BotError: Error communicating with bot GPT-4o

**Comment by qingyanbaby** [comment]
<img width="858" alt="image" src="https://github.com/user-attachments/assets/50e88155-744d-498d-8e47-ba95de7b5487" />
Configure it like this.

```
CUSTOM_TOKEN=sk-123456
SYSTEM_TOKEN=poe-api-key
```

The POE API key needs to be set in the environment variables of this project, not in the calling code. In the calling code, you should use your own custom key.

**Comment by tqosu** [comment]
CUSTOM_TOKEN=sk-123456
SYSTEM_TOKEN=QKwxvyhHuq1QH1XMZ54ths4LVE83dQshSR48JIAVAwo
MODEL_MAPPING='{
    "gpt-3.5-turbo": "GPT-3.5-Turbo",
    "gpt-4o": "GPT-4o",
    "gpt-4-turbo": "GPT-4-Turbo"
}'
PROXY_TYPE=socks
PROXY_HOST=127.0.0.1
PROXY_PORT=6668
PROXY_USERNAME=
PROXY_PASSWORD=

```
# python demo
from openai import OpenAI

client = OpenAI(
  # 自定义校验token
  api_key='sk-123456',
  base_url='http://127.0.0.1:39527/v1'
)
messages = [
  {"role": "system", "content": "You are a helpful assistant."},
  {"role": "user", "content": "Hello, who won the world series in 2020?"}
]
response = client.chat.completions.create(
  model="gpt-4o",
  messages=messages,
  stream=False
)

print(response.choices[0].message)
```

**Comment by tqosu** [comment]
It triggers the same error.

**Comment by qingyanbaby** [comment]
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/dfc45d43-034e-41f7-b474-226ac1121a3c" />
I tested your key, and it works fine. If you're not concerned about leaking it, you can directly use the POE API key for the calls, but don't add the 'sk-' prefix. Your current issue might be related to the proxy server. Ensure that your proxy server actually exists, or set it to an empty value if it doesn't.

You now need to regenerate the POE API key because you have already exposed it in plain text here.

**Comment by tqosu** [comment]
Yes. I regenerated the key and set the proxy to empty
```
PROXY_TYPE=
PROXY_HOST=
PROXY_PORT=
PROXY_USERNAME=
PROXY_PASSWORD=
```
But it still doesn't work and I have no idea how to fix it.

```
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:39527 (Press CTRL+C to quit)
INFO:     127.0.0.1:52394 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52394 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:49172 - "GET /v1 HTTP/1.1" 404 Not Found

```

**Comment by qingyanbaby** [comment]
`PROXY_TYPE=` should not be empty.Also, ensure that you are using the latest code.

**Comment by tqosu** [comment]
Thanks. It works!
